var errorConstants = {
  ERRORS_RECEIVED: 'ERRORS_RECEIVED',
  LOGIN_ERRORS_CLEARED: 'LOGIN_ERRORS_CLEARED',
  PASSWORD_ERROR: 'PASSWORD_ERROR',
  SIGN_UP_ERROR_CLEARED: 'SIGN_UP_ERROR_CLEARED',
  SIGN_UP_ERRORS_CLEARED: 'SIGN_UP_ERRORS_CLEARED'
};

module.exports = errorConstants;
