var errorConstants = {
  CLOSE_ALL: 'CLOSE_ALL',
  INTRO_DESCRIPTION_CLOSE: 'INTRO_DESCRIPTION_CLOSE',
  INTRO_DESCRIPTION_OPEN: 'INTRO_DESCRIPTION_OPEN',
  INTRO_WORK_CLOSE: 'INTRO_WORK_CLOSE',
  INTRO_WORK_OPEN: 'INTRO_WORK_OPEN',
  INTRO_SCHOOL_CLOSE: 'INTRO_SCHOOL_CLOSE',
  INTRO_SCHOOL_OPEN: 'INTRO_SCHOOL_OPEN',
  INTRO_LOCATION_CLOSE: 'INTRO_LOCATION_CLOSE',
  INTRO_LOCATION_OPEN: 'INTRO_LOCATION_OPEN',
  INTRO_HOMETOWN_CLOSE: 'INTRO_HOMETOWN_CLOSE',
  INTRO_HOMETOWN_OPEN: 'INTRO_HOMETOWN_OPEN'
};

module.exports = errorConstants;
