var friendRequestConstants = {
  MADE_FRIEND_REQUEST_RECEIVED: 'MADE_FRIEND_REQUEST_RECEIVED',
  FRIEND_REQUEST_CANCELED: 'FRIEND_REQUEST_CANCELED',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_REJECTED: 'FRIEND_REQUEST_REJECTED'
};

module.exports = friendRequestConstants;
