var friendRequestConstants = {
  CHECKED_FRIEND_REQUEST_IDS_RECEIVED: 'CHECKED_FRIEND_REQUEST_IDS_RECEIVED',
  CHECKING_REQUESTS_NOW: 'CHECKING_REQUESTS_NOW',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUESTS_RECEIVED: 'FRIEND_REQUESTS_RECEIVED',
  MADE_FRIEND_REQUEST_CANCELED: 'MADE_FRIEND_REQUEST_CANCELED',
  MADE_FRIEND_REQUEST_RECEIVED: 'MADE_FRIEND_REQUEST_RECEIVED',
  RECEIVED_FRIEND_REQUEST_ACCEPTED: 'RECEIVED_FRIEND_REQUEST_ACCEPTED',
  RECEIVED_FRIEND_REQUEST_REJECTED: 'RECEIVED_FRIEND_REQUEST_REJECTED',
  RECEIVED_FRIEND_REQUEST_RECEIVED: 'RECEIVED_FRIEND_REQUEST_RECEIVED'
};

module.exports = friendRequestConstants;
