var friendRequestConstants = {
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUESTS_RECEIVED: 'FRIEND_REQUESTS_RECEIVED',
  MADE_FRIEND_REQUEST_ACCEPTED: 'MADE_FRIEND_REQUEST_ACCEPTED',
  MADE_FRIEND_REQUEST_CANCELED: 'MADE_FRIEND_REQUEST_CANCELED',
  MADE_FRIEND_REQUEST_RECEIVED: 'MADE_FRIEND_REQUEST_RECEIVED',
  RECEIVED_FRIEND_REQUEST_ACCEPTED: 'RECEIVED_FRIEND_REQUEST_ACCEPTED',
  RECEIVED_FRIEND_REQUEST_REJECTED: 'RECEIVED_FRIEND_REQUEST_REJECTED',
  RECEIVED_FRIEND_REQUEST_RECEIVED: 'RECEIVED_FRIEND_REQUEST_RECEIVED'
};

module.exports = friendRequestConstants;
