var notificationConstants = {
  CHECKED_NOTIFICATION_IDS_RECEIVED: 'CHECKED_NOTIFICATION_IDS_RECEIVED',
  NOTIFICATION_CHECKED: 'NOTIFICATION_CHECKED',
  NOTIFICATIONS_RECEIVED: 'NOTIFICATIONS_RECEIVED'
};

module.exports = notificationConstants;
