var postConstants = {
  DELETED_POST_RECEIVED: 'DELETED_POST_RECEIVED',
  EDITING_POST: 'EDITING_POST',
  EDITING_FINISHED: 'EDITING_FINISHED',
  OWN_POST_RECEIVED: 'OWN_POST_RECEIVED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  TAGGED_FRIENDS_RECEIVED: 'TAGGED_FRIENDS_RECEIVED',
  UPDATED_POST_RECEIVED: 'UPDATED_POST_RECEIVED'
};

module.exports = postConstants;
