var postConstants = {
  DELETED_POST_RECEIVED: 'DELETED_POST_RECEIVED',
  OWN_POST_RECEIVED: 'OWN_POST_RECEIVED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  UPDATED_POST_RECEIVED: 'UPDATED_POST_RECEIVED'
};

module.exports = postConstants;
