var tagConstants = {
  FRIENDS_RECEIVED_FOR_TAGGING: 'FRIENDS_RECEIVED_FOR_TAGGING',
  FRIEND_TAGGED: 'FRIEND_TAGGED',
  FRIEND_UNTAGGED: 'FRIEND_UNTAGGED',
  TAG_SEARCH_RESULTS_RECEIVED: 'TAG_SEARCH_RESULTS_RECEIVED'
};

module.exports = tagConstants;
