var tagConstants = {
  FREEZE_TAGS: 'FREEZE_TAGS',
  FRIENDS_RECEIVED_FOR_TAGGING: 'FRIENDS_RECEIVED_FOR_TAGGING',
  FRIEND_TAGGED: 'FRIEND_TAGGED',
  FRIEND_UNTAGGED: 'FRIEND_UNTAGGED',
  TAG_SEARCH_RESULTS_RECEIVED: 'TAG_SEARCH_RESULTS_RECEIVED',
  UNFREEZE_TAGS: 'UNFREEZE_TAGS'
};

module.exports = tagConstants;
