var userConstants = {
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
  CURRENT_USER_REMOVED: "CURRENT_USER_REMOVED",
  UPDATED_COVER_PHOTO_URL_RECEIVED: 'UPDATED_COVER_PHOTO_URL_RECEIVED',
  UPDATED_PROFILE_PIC_URL_RECEIVED: 'UPDATED_PROFILE_PIC_URL_RECEIVED',
  USERS_RECEIVED: 'USERS_RECEIVED',
  USER_RECEIVED: 'USER_RECEIVED'
};

module.exports = userConstants;
