var userConstants = {
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
  CURRENT_USER_REMOVED: "CURRENT_USER_REMOVED",
  USERS_RECEIVED: 'USERS_RECEIVED',
  USER_RECEIVED: 'USER_RECEIVED'
};

module.exports = userConstants;
