# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1904cc544a29131a5a2400ff26cd7d14154434f1e7e6f0d2beaefa6176d0a655771e9ae66f6a7244678528d70df497ee07c2931a05dc640742213b01a136d8

test:
  secret_key_base: 3bfd30a2e207ccec3bdf543fc467c581892a35b2bc03ea3ebadaa8689860b0247c0f5c43c7559f15351aedb9836742144c5fc78905a996ca5dde3e201853b0c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
